### ISSUE TITLE
Trouble installing TEPPP with gcc version 7: <filesystem> not recognized

### ISSUE THREAD

**Issue by samlobe** [Zer0F8th/TEPPP#7]
<hr>

## Describe the bug

Unable to install this software with `make all` or `make serial` even though my compiler is gcc version 7.

## Error messages, stack traces, etc.

> make serial
Convertor Compilation Success
g++ main/convertor.cpp -o convertor
main/convertor.cpp:2:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
make: *** [convertor] Error 1

## Version information

- Compiler: gcc
- Compiler version: 7.1.0
- Operating system: Linux
- Operating system version: When I do `uname -a` on my cluster I get "UTC 2015 x86_64 x86_64 x86_64 GNU/Linux"

**Comment by Zer0F8th** [comment]
This isn't the official repo I linked, this is my own personal fork which is outdated. 

The official repo can be found here:
https://github.com/TEPPP-software/TEPPP

The reason you are getting this error is due to the fact that `GCC v7` still does not implement <filesystem> but it does have the *Filesystem Technical Specification* which is in [<experimental/filesystem>](https://en.cppreference.com/w/cpp/header/experimental/filesystem)

Prior to GCC8 the filesystem library had to be implemented adding `experimental` to the #include, like so:
```c++
#include <experimental/filesystem>

namespace fs = std::experimental::filesystem;

int main()
{
    fs::path p = "/path/to/my/file"; // etc...
}
```

With `GCC v8` this is no longer necessary and can be implemented like so:

```c++
#include <filesystem>
...
```
I will work on a fix that support older GCC versions, but for now only gcc-8 and above is supported
